### ISSUE TITLE
Setup not working with PTManager.swift

### ISSUE THREAD

**Issue by PaperMashe** [kirankunigiri/peertalk-simple#7]
Hi, I tried to do as told in the guide and just copy the PTManager.swift from Source folder, but it was giving me a lot of errors, then I tried to copy the whole structure together with the peertalk folder and helper.swift and PeertalkSimple-Bridging-Header.h and it is still giving me a lot of errors, I am very new to swift and I presume that the guide is for a bit more advanced people than me and unfortunately I am stuck and I didn't find any other guides on the internet about peertalk-simple so I thought I'd ask at the source.  I'd appreciate any help that you could give me. Thanks 
<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/53487942/83948848-231ce880-a818-11ea-81cf-59abcff9f104.png">

also PS: I am trying to make an app for my own needs that would send the iPhone camera feed over to the mac as a second webcam. There is a bunch of such apps in the AppStore for around €20 in my location which is a bit pricey if I do say so myself so I thought I might try and make one of my own while learning new skills...  could I transfer a video stream over USB with peertalk/peertalk-simple? Is it technically possible to send video files?

**Comment by cbjeukendrup** [comment]
I hope I can help you by the following:
1. Rename "PeertalkSimple-Bridging-Header.h" to "iOScameraFeed-Bridging-Header.h". This is the file that will import any Objective-C code so that you can use it in your Swift files. 
2. Open your project file (that blue one at the top of the list) and select your app's target. Go to the "Build Settings" tab. 
3. Search for `Objective-C Bridging Header`. Set the value of this settings to "iOScameraFeed-Bridging-Header.h".

By the way: I like that you thought "Oh, that costs money, let's make it myself!" I also did that, with another app. I think it's so nice, because it saves a lot of money, gives you a nice project to work on this summer and let's you make an app just how *you* like it (which may be even better than the original).

**Comment by PaperMashe** [comment]
Yes, it worked! Okay, the integration part worked... Now the next part – figure out how to use the `AVCaptureMovieFileOutput` with it so it can send live video output over TCP! ...I am not going to lie, I kind of postponed the project, as I wasn't sure if I'll be able to make the integration part work at all and didn't find any other open-source ways of sending data over the cable, but now I can get back into it so thank you very much for your help! :))

**Comment by cbjeukendrup** [comment]
Ah, so happy to hear that! Good luck with your app!
Maybe we should close this ‘issue’ now, to let the author of “PeertalkSimple” know that it’s solved.

One more thing: I think it’s for sure possible to send video over Peertalk! This app also uses Peertalk and even turns an iDevice into a secondary display: https://apps.apple.com/nl/app/duet-display/id935754064
